name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Format code
        run: npm run format

      - name: Build code
        run: npm run build

      - name: Remote SSH Commands
        uses: fifsky/ssh-action@v0.0.6
        with:
          host: ${{ secrets.EC2_SSH_HOST }}
          user: ${{ secrets.EC2_SSH_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          command: |
            pm2 stop all
            cd ${{ github.event.repository.name }}
            git pull
            npm install
            npm run build
            pm2 start all
